var body = document.querySelector("body");
var contact_form = document.getElementsByClassName("contact_form")[0];

var headers = ["purple_header", "red_header", "turquoise_header"],
	hovers = ["purple_hover", "red_hover", "turquoise_hover"],
	btn_hovers = ["purple_btn_hover", "red_btn_hover", "turquoise_btn_hover"],
	focuses = ["purple_focus", "red_focus", "turquoise_focus"],
	header_btns = ["purple_header_button", "red_header_button", "turquoise_header_button"],
	colors = ["purple", "red", "turquoise"],
	bgs = ["purple_bg", "red_bg", "turquoise_bg"],
	styles = ["purple_style", "red_style", "turquoise_style"],

	icons = [["purple_icon_1","purple_icon_2", "purple_icon_3"],
			 ["red_icon_1", "red_icon_2", "red_icon_3"],
			 ["turquoise_icon_1", "turquoise_icon_2", "turquoise_icon_3"]
			],

	imgs = [["purple_img_1", "purple_img_2", "purple_img_3", "purple_img_4"],
			["red_img_1", "red_img_2", "red_img_3", "red_img_4"],
			["turquoise_img_1", "turquoise_img_2" , "turquoise_img_3", "turquoise_img_4"]
		   ],
	socials = [["purple_social_1", "purple_social_2", "purple_social_3"],
			   ["red_social_1", "red_social_2", "red_social_3"],
			   ["turquoise_social_1", "turquoise_social_2", "turquoise_social_3"]],

	default_header_class = "header_images",
	default_logo_class = "logo",
	default_nav_link_class = "nav_link",
	default_header_btn_class = "header_button",
	default_name_title_class = "name_title",
	default_skill_title_class = "skill_title",
	default_icon_classes = ["icon_1", "icon_2", "icon_3"],
	default_img_class = "gallery_img",
	default_img_info_class = "img_info",
	default_img_btn_class = "img_button",
	default_gallery_btn_class = "gallery_button",
	default_contact_title_class = "contact_title",
	default_inputs_classes = ["name_input form_style", "email_input form_style", "textarea form_style"],
	default_footer_class = "footer_main",
	default_social_item_class = "social_item",
	default_social_icon_class = "social_icon";

var header = document.getElementsByClassName(default_header_class)[0],
	logo = document.getElementsByClassName(default_logo_class)[0],
	nav_links = document.getElementsByClassName(default_nav_link_class),
	header_btn = document.getElementsByClassName(default_header_btn_class)[0],
	name_title = document.getElementsByClassName(default_name_title_class)[0],
	skill_titles = document.getElementsByClassName(default_skill_title_class),
	skill_icons = [document.getElementsByClassName(default_icon_classes[0])[0],
			 	   document.getElementsByClassName(default_icon_classes[1])[0],
			 	   document.getElementsByClassName(default_icon_classes[2])[0]],
	gallery_imgs = document.getElementsByClassName(default_img_class),
	gallery_infos = document.getElementsByClassName(default_img_info_class),
	gallery_img_btns = document.getElementsByClassName(default_img_btn_class),
	gallery_button = document.getElementsByClassName(default_gallery_btn_class)[0],
	contact_title = document.getElementsByClassName(default_contact_title_class)[0],
	inputs = [document.getElementsByClassName(default_inputs_classes[0])[0],
			  document.getElementsByClassName(default_inputs_classes[1])[0],
			  document.getElementsByClassName(default_inputs_classes[2])[0]],
	footer = document.getElementsByClassName(default_footer_class)[0],
	social_items = document.getElementsByClassName(default_social_item_class),
	social_icons = document.getElementsByClassName(default_social_icon_class);